CREATE TABLE `USER`(
  USUARIO mediumint(9) NOT NULL,
  PASS binary(16) NOT NULL
);


INSERT INTO USER VALUES('1',UNHEX(MD5('1'))); 
INSERT INTO USER VALUES('2',UNHEX(MD5('2'))); 
INSERT INTO USER VALUES('3',UNHEX(MD5('3'))); 
INSERT INTO USER VALUES('4',UNHEX(MD5('4'))); 
INSERT INTO USER VALUES('5',UNHEX(MD5('5'))); 
INSERT INTO USER VALUES('6',UNHEX(MD5('6'))); 
INSERT INTO USER VALUES('7',UNHEX(MD5('7'))); 
INSERT INTO USER VALUES('8',UNHEX(MD5('8'))); 
INSERT INTO USER VALUES('9',UNHEX(MD5('9'))); 
INSERT INTO USER VALUES('10',UNHEX(MD5('10'))); 
INSERT INTO USER VALUES('11',UNHEX(MD5('11'))); 
INSERT INTO USER VALUES('12',UNHEX(MD5('12'))); 
INSERT INTO USER VALUES('13',UNHEX(MD5('13'))); 
INSERT INTO USER VALUES('14',UNHEX(MD5('14'))); 
INSERT INTO USER VALUES('15',UNHEX(MD5('15'))); 
INSERT INTO USER VALUES('16',UNHEX(MD5('16'))); 
INSERT INTO USER VALUES('17',UNHEX(MD5('17'))); 
INSERT INTO USER VALUES('18',UNHEX(MD5('18'))); 
INSERT INTO USER VALUES('19',UNHEX(MD5('19'))); 
INSERT INTO USER VALUES('20',UNHEX(MD5('20'))); 
INSERT INTO USER VALUES('21',UNHEX(MD5('21'))); 
INSERT INTO USER VALUES('22',UNHEX(MD5('22'))); 
INSERT INTO USER VALUES('23',UNHEX(MD5('23'))); 
INSERT INTO USER VALUES('24',UNHEX(MD5('24'))); 
INSERT INTO USER VALUES('25',UNHEX(MD5('25'))); 
INSERT INTO USER VALUES('26',UNHEX(MD5('26'))); 
INSERT INTO USER VALUES('27',UNHEX(MD5('27'))); 
INSERT INTO USER VALUES('28',UNHEX(MD5('28'))); 
INSERT INTO USER VALUES('29',UNHEX(MD5('29'))); 
INSERT INTO USER VALUES('30',UNHEX(MD5('30'))); 
INSERT INTO USER VALUES('31',UNHEX(MD5('31'))); 
INSERT INTO USER VALUES('32',UNHEX(MD5('32'))); 
INSERT INTO USER VALUES('33',UNHEX(MD5('33'))); 
INSERT INTO USER VALUES('34',UNHEX(MD5('34'))); 
INSERT INTO USER VALUES('35',UNHEX(MD5('35'))); 
INSERT INTO USER VALUES('36',UNHEX(MD5('36'))); 
INSERT INTO USER VALUES('37',UNHEX(MD5('37'))); 
INSERT INTO USER VALUES('38',UNHEX(MD5('38'))); 
INSERT INTO USER VALUES('39',UNHEX(MD5('39'))); 
INSERT INTO USER VALUES('40',UNHEX(MD5('40'))); 
INSERT INTO USER VALUES('41',UNHEX(MD5('41'))); 
INSERT INTO USER VALUES('42',UNHEX(MD5('42'))); 
INSERT INTO USER VALUES('43',UNHEX(MD5('43'))); 
INSERT INTO USER VALUES('44',UNHEX(MD5('44'))); 
INSERT INTO USER VALUES('45',UNHEX(MD5('45'))); 
INSERT INTO USER VALUES('46',UNHEX(MD5('46'))); 
INSERT INTO USER VALUES('47',UNHEX(MD5('47'))); 
INSERT INTO USER VALUES('48',UNHEX(MD5('48'))); 
INSERT INTO USER VALUES('49',UNHEX(MD5('49'))); 
INSERT INTO USER VALUES('50',UNHEX(MD5('50'))); 
INSERT INTO USER VALUES('51',UNHEX(MD5('51'))); 
INSERT INTO USER VALUES('52',UNHEX(MD5('52'))); 
INSERT INTO USER VALUES('53',UNHEX(MD5('53'))); 
INSERT INTO USER VALUES('54',UNHEX(MD5('54'))); 
INSERT INTO USER VALUES('55',UNHEX(MD5('55'))); 
INSERT INTO USER VALUES('56',UNHEX(MD5('56'))); 
INSERT INTO USER VALUES('57',UNHEX(MD5('57'))); 
INSERT INTO USER VALUES('58',UNHEX(MD5('58'))); 
INSERT INTO USER VALUES('59',UNHEX(MD5('59'))); 
INSERT INTO USER VALUES('60',UNHEX(MD5('60'))); 
INSERT INTO USER VALUES('61',UNHEX(MD5('61'))); 
INSERT INTO USER VALUES('62',UNHEX(MD5('62'))); 
INSERT INTO USER VALUES('63',UNHEX(MD5('63'))); 
INSERT INTO USER VALUES('64',UNHEX(MD5('64'))); 
INSERT INTO USER VALUES('65',UNHEX(MD5('65'))); 
INSERT INTO USER VALUES('66',UNHEX(MD5('66'))); 
INSERT INTO USER VALUES('67',UNHEX(MD5('67'))); 
INSERT INTO USER VALUES('68',UNHEX(MD5('68'))); 
INSERT INTO USER VALUES('69',UNHEX(MD5('69'))); 
INSERT INTO USER VALUES('70',UNHEX(MD5('70'))); 
INSERT INTO USER VALUES('71',UNHEX(MD5('71'))); 
INSERT INTO USER VALUES('72',UNHEX(MD5('72'))); 
INSERT INTO USER VALUES('73',UNHEX(MD5('73'))); 
INSERT INTO USER VALUES('74',UNHEX(MD5('74'))); 
INSERT INTO USER VALUES('75',UNHEX(MD5('75'))); 
INSERT INTO USER VALUES('76',UNHEX(MD5('76'))); 
INSERT INTO USER VALUES('77',UNHEX(MD5('77'))); 
INSERT INTO USER VALUES('78',UNHEX(MD5('78'))); 
INSERT INTO USER VALUES('79',UNHEX(MD5('79'))); 
INSERT INTO USER VALUES('80',UNHEX(MD5('80'))); 
INSERT INTO USER VALUES('81',UNHEX(MD5('81'))); 
INSERT INTO USER VALUES('82',UNHEX(MD5('82'))); 
INSERT INTO USER VALUES('83',UNHEX(MD5('83'))); 
INSERT INTO USER VALUES('84',UNHEX(MD5('84'))); 
INSERT INTO USER VALUES('85',UNHEX(MD5('85'))); 
INSERT INTO USER VALUES('86',UNHEX(MD5('86'))); 
INSERT INTO USER VALUES('87',UNHEX(MD5('87'))); 
INSERT INTO USER VALUES('88',UNHEX(MD5('88'))); 
INSERT INTO USER VALUES('89',UNHEX(MD5('89'))); 
INSERT INTO USER VALUES('90',UNHEX(MD5('90'))); 


CREATE TABLE DATOS(
  USUARIO mediumint(9) NOT NULL,
  fecha DATETIME NOT NULL,
  IPServidor varchar(16) NOT NULL,
  MemTotal varchar(16) NOT NULL,
  MenPLibre varchar(6) NOT NULL,
  MenUsada varchar(16) NOT NULL,
  MenPUsada varchar(6) NOT NULL,
  CPU varchar(6) NOT NULL,
  IPCliente varchar(16) NOT NULL,
  Sistema varchar(5) NOT NULL,
  Navegador varchar(9) NOT NULL,
  Pantalla varchar(10) NOT NULL,
  tiempo_acceso varchar(6) NOT NULL,
);




